### ISSUE TITLE
Value shown wrong (value /1000)

### ISSUE THREAD

**Issue by patbecks** [EmDee/moneymoney-bondora#15]
With Version 1.30 there is now a problem with the decimal/thousand separators. Value of 1.080 € becomes 1,08 € in MM

**Comment by EmDee** [comment]
@patbecks That is intended, but should not happen, because I'm enforcing the English locale where the thousand separator should be a `,` and the decimal separator a `.`, unless Bondora is doing funny things. Can you send me your output of https://www.bondora.com/en/dashboard/overviewnumbers/ (either here or via support@martindinh.de)?

**Comment by patbecks** [comment]
thank you for your quick response.
I changed my Account preferences @: https://www.bondora.com/en/account#managepreferences 
decimal `.` and thousand separator  `,` 
Now its working correctly

**Comment by EmDee** [comment]
Thanks for checking! I didn't even know that that was possible. This could definitely lead to problems for others as well.

Maybe the best course here is to go for the `value` instead of `valuetooltip`, it will not be 100% precise, but I guess the decimal places are not too relevant anyway. I'll wait and see how many people report a problem and act accordingly.
